kick_message: "Maintenance is active, you may not join this server until the potential problem is resolved"
maintenance_information:
  active: true
  link: "https://www.example.com"
#Time until players get disconnected (in seconds)
time: 30